### ISSUE TITLE
LG AC and Heat Pump Support

### ISSUE THREAD

**Issue by bzumik1** [JanM321/esphome-lg-controller#21]
Hi, I plan to buy **LG AC UM36F + UUC1 Comfort** and **LG Heat Pump HN0913T.NK0 + HU051MR.U44**. Can I ask of they are supported?

**Comment by JanM321** [comment]
> Hi, I plan to buy **LG AC UM36F + UUC1 Comfort** and **LG Heat Pump HN0913T.NK0 + HU051MR.U44**. Can I ask of they are supported?

I expect the AC units to be compatible, but I haven't seen these models before so I can't guarantee it will work. The air/water heat pump will likely need a different solution. I think it's possible to connect via modbus but I don't know more about this.

**Comment by JanM321** [comment]
If you're able to test the controller with these units please let me know so I can add them to the README.

**Comment by bzumik1** [comment]
Ok as I will receive them I will test that.

**Comment by JanM321** [comment]
It *might* work. The protocol implemented here seems AC specific, but maybe the heat pump one is similar enough? There was a similar question in #14.
