### ISSUE TITLE
M5Stack ATOM Lite + ATOMIC RS485 Base

### ISSUE THREAD

**Issue by bzumik1** [JanM321/esphome-lg-controller#22]
Hi, can I use the [M5Stack ATHOM Lite](https://docs.m5stack.com/en/core/ATOM%20Lite) and [M5Stack ATOMIC RS485 Base](https://docs.m5stack.com/en/atom/Atomic%20RS485%20Base) to control LG AC? I know that the M5Stack ATOMIC RS485 Base is meant for RS485, but base on my understanding I should be able to use 12V, Ground and A or B port for data (the second one would stay unpluged). Could you please advice if that would work?

**Comment by JanM321** [comment]
I don't know, I'm not familiar with RS485. Based on what I'm seeing it probably won't work though. If you want to use an Atom Lite see issue #2.
