### ISSUE TITLE
using home assistant temperature sensor.

### ISSUE THREAD

**Issue by cwtufts** [JanM321/esphome-lg-controller#35]
I am trying to figure out how to use a home assistant temperature sensor entity. Which file should that be placed in?

**Comment by JanM321** [comment]
The template YAML file has this line:
```yaml
temperature_sensor_entity_id: sensor.my_sensor # XXX
```
Here you should put the entity id of the Home Assistant temperature sensor you want the controller to use.

If you want to use a template sensor, you can put those in Home Assistant's configuration file. I have mine in configuration.yaml.

**Comment by cwtufts** [comment]
Okay that is what I have. For some reason it is reading 95 F when the temperature is 73.89. Could this be an issue of the temp being in F instead of C?

![Screenshot 2024-02-15 at 10 08 37 (2)](https://github.com/JanM321/esphome-lg-controller/assets/82612124/e043441d-50fd-4285-8872-fdc54ace49c7)

**Comment by JanM321** [comment]
> Okay that is what I have. For some reason it is reading 95 F when the temperature is 73.89. Could this be an issue of the temp being in F instead of C?

Oh right, Fahrenheit isn't well supported atm. See also issue #27

**Comment by JanM321** [comment]
I made some changes to better support Fahrenheit. You can set the Fahrenheit option to "true" in the template yaml file with the latest version. Please let me know if this works better now.

**Comment by JanM321** [comment]
Closing because the new Fahrenheit mode fixes this.
