### ISSUE TITLE
Additional supported LG models

### ISSUE THREAD

**Issue by kchen** [JanM321/esphome-lg-controller#36]
I've used the following units in my house with this project, so feel free to add these to the supported devices list if desired:

Indoor units:
LMN079HVT
LSN090HSV5

Outdoor unit:
LMU361HHV

**Comment by JanM321** [comment]
Thanks, I added them to the list.

I'm also glad you reported the Fahrenheit issue. I didn't realize this was an issue but it's good that just works now.

**Comment by seatrope** [comment]
@kchen Thanks for reporting this! I have the LSN090HSV5 too, any tips or pitfalls for installation or was it pretty straightforward? Which PCB version did you use?
