### ISSUE TITLE
Unclear controls exposed

### ISSUE THREAD

**Issue by sergeipr** [JanM321/esphome-lg-controller#56]
Hi,
I have connected a board to ARNU36GBGA2 duct unit, in parallel with PREMTB001 controller set to slave mode.
The unit seems to work, but I don't understand the HA exposed controls for Fan Speed.
<img width="333" alt="image" src="https://github.com/JanM321/esphome-lg-controller/assets/18151370/c3ce999c-70ff-44d5-b7ad-9e494d91161e">
I have an option to modify the 3 values (low, medium, high see screenshot), but what do these values represent? 

Here are the C9 and CA codes
[15:46:48][D][lg-controller:943]: received C9.12.EB.5C.26.32.00.84.13.00.00.00.44 (13)
[15:46:48][D][lg-controller:943]: received CA.00.00.00.64.00.00.00.00.02.F1.01.77 (13)

Another observation - there is an option to set Fan speed to Auto mode via Sub-Function button, but auto fan is not available HA UI

**Comment by JanM321** [comment]
These correspond to the ESP Value installer setting (installer setting 3). It lets you adjust the fan speed for the Low/Medium/High fan modes.

**Comment by JanM321** [comment]
I clarified this a bit in the README. Does that answer your question?
