### ISSUE TITLE
Current Temperature missing

### ISSUE THREAD

**Issue by Arunas-g** [JanM321/esphome-lg-controller#60]
Hello. I have a problem getting "Current Temperature" from my LG TC07GQR air conditioner. I have another LG air conditioner, model PC12SQ, it works perfectly. In the logs, instead of the temperature, it says “nan°C”

`[15:01:01][D][climate:419]:   Current Temperature: nan°C`
`[15:01:01][D][climate:425]:   Target Temperature: 26.00°C`

At the same time, the air conditioner itself works normally, reacts to changes in “Target Temperature” and automatically changes the air flow rate. Air conditioner control is organized using "hardware-tiny". Please help me understand the reason for the incorrect display of the target temperature.

I attach logs and screenshots
[logs_Current Temperature nan C.txt](https://github.com/user-attachments/files/16108666/logs_Current.Temperature.nan.C.txt)
![image](https://github.com/JanM321/esphome-lg-controller/assets/58878676/3df85e50-84a2-441e-a978-eebb41ae8d67)

**Comment by JanM321** [comment]
It's using `sensor.ac_lg_linas` as room temperature sensor. Is that a sensor you have available in Home Assistant? Can you show information about that one?

**Comment by JanM321** [comment]
Basically your options are:
1. Set the "Internal Thermistor" setting to On to use the temperature value measured by the AC.
2. Make sure `sensor.ac_lg_linas` is a valid temperature sensor in Home Assistant because it will be *read* by the controller.

**Comment by Arunas-g** [comment]
I apologize for the trouble :) I turned on "Internal Thermistor" and after that "Current Temperature" is displayed correctly in the logs.
Thank you!

![image](https://github.com/JanM321/esphome-lg-controller/assets/58878676/c97a41c7-4b34-4bb5-a4e5-7347e64bb7ea)

![image](https://github.com/JanM321/esphome-lg-controller/assets/58878676/3a9ca99d-3d22-4d79-b5bd-3a05fe300897)

**Comment by JanM321** [comment]
No problem. I’m glad that works :)
