### ISSUE TITLE
How to connect Wired controller to Airco Unit

### ISSUE THREAD

**Issue by belly-89** [JanM321/esphome-lg-controller#7]
Hi,

Really cool project, I just placed an request at PCBway including assembly, hopefully everything goes smoothly.

I haven't opened the LG indoor unit (S12ET) yet, and since I can't find it online anywhere, it might be a stupid question. But is there anywhere that describes how to connect the controller to the indoor unit? Is there perhaps a video or something like that available?

Thanks in advance.

**Comment by JanM321** [comment]
The unit might have a CN-REMO socket (probably green) on the PCB and you can use a 3-pin JST-XH cable to connect to it. See the list of materials in this repository for the one I used. My units also came with a small extension cable plugged into the CN-REMO port.

Unfortunately some units don't have a CN-REMO socket soldered on the PCB, see #6 for example.

**Comment by belly-89** [comment]
![PXL_20231019_175306174](https://github.com/JanM321/esphome-lg-controller/assets/20487796/f5e20da8-903c-4333-ba6e-5bff82284adc)
Ah thanks! Just opened the bottom and indeed a cable that looks like what I need. Now waiting on PCway for approval of the design including assembly. 

Thanks!

**Comment by JanM321** [comment]
Nice, that looks like what I have here.

My controllers are connected to that with a long extension cable from LG (LG PZCWRCG1 or PZCWRCG3) that they also include with their wall controllers. You could either do that or put the PCB inside the AC unit somehow.

**Comment by belly-89** [comment]
Thanks!! I already have a short cable with a 3-pin JST-XH connector on it. I was thinking of simply extending it by soldering the wires to a longer cable so that I can hide it well. Do I not need to order an extra cable!
