### ISSUE TITLE
How to link HA sensor as external sensor

### ISSUE THREAD

**Issue by drbugfinder** [JanM321/esphome-lg-controller#70]
Hello!

I just bought a couple of the SONOFF ZNZB-02D sensors (update rate of 5 seconds) and connected them via zigbee2mqtt to HA. Can someone please explain (and document) how exactly such a HA sensor can be used as an external sensor for the controller? 

https://github.com/JanM321/esphome-lg-controller/issues/43 does not help here

Thanks

**Comment by JanM321** [comment]
In Home Assistant your sensor has an entity id, something like `sensor.mysensor`. That’s the id you have to put in the yaml file. That’s all.
