### ISSUE TITLE
Fan speed options

### ISSUE THREAD

**Issue by SiboutVanLoo** [JanM321/esphome-lg-controller#71]
Hi there Jan,

I noticed the fan speeds are limited in most cases. Eg. silent mode,...

This is what i pick up from LQthinq integration:
hvac_modes: off, heat, dry, cool, fan_only, heat_cool
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: low, LOW_MID, medium, MID_HIGH, high, diffuse
swing_modes: VerticalOff, VerticalTop, VerticalMiddleTop1, VerticalMiddleTop2, VerticalMiddleBottom2, VerticalMiddleBottom1, VerticalBottom, VerticalSwing, HorizontalOff, HorizontalLeft, HorizontalMiddleLeft, HorizontalCenter, HorizontalMiddleRight, HorizontalRight, HorizontalLeftHalf, HorizontalRightHalf, HorizontalSwing
current_temperature: 24.5
temperature: 25
fan_mode: low
swing_mode: VerticalOff
swing_mode_horizontal: HorizontalCenter
swing_mode_vertical: VerticalOff
friendly_name: AC Living
supported_features: 425

VS ESPHOME:

hvac_modes: off, heat_cool, cool, heat, fan_only, dry
min_temp: 16
max_temp: 30
target_temp_step: 0.5
fan_modes: auto, low, medium, high
swing_modes: off, both, vertical, horizontal
current_temperature: 24.5
temperature: 25
fan_mode: low
swing_mode: off
friendly_name: lglivingesp 
supported_features: 425

I'dont know for shure if the wired thermostat from LG supports the extra fan speeds, but i do think so. IR does.
Fanmode "diffuse" = auto

I can check what the logs say when set at an "unavailable" speed. But after my vacation. 😄

Thanks for the great project!
Loving life without millions and billions and billions of beeps! ❤️

**Comment by JanM321** [comment]
Unfortunately this is an issue with the wired controllers. The controllers support low-medium and medium-high but most units report they don't support it and don't accept these values.

See #28.
