### ISSUE TITLE
LG PC12SQ PCB to buy?

### ISSUE THREAD

**Issue by Tweak-NL** [JanM321/esphome-lg-controller#74]
Hello, i have the LG PC12SQ with wifi module but i prefer to control this AC in HA without the LG cloud thingy. Does someone here have a PCB that i can buy? Or a cheap way to get it? I only have 1 AC in this house. I am from the Netherlands maybe JanM321 can help me out?

**Comment by JanM321** [comment]
I don't have any spare PCBs. Maybe @tach2004 (from #69)?

**Comment by evertide** [comment]
I have one you can have at cost. Please send me a dm on the tweakers website to evert)ide
