### ISSUE TITLE
F09MT fan speed 

### ISSUE THREAD

**Issue by djbiti1** [JanM321/esphome-lg-controller#75]
Hello

I can confirm the F09MT works fine with this integration.
This is the capabilities message:
	C9.C4.E8.1F.81.71.00.C0.02.40.04.81.58
	
Unfortunately I see the medium-low and medium-high are not supported, even though the remote allows it. What happens if you send the command for these modes anyway? Will the unit just ignore them? How could I test this? 
Also I see the power fan speed is supported but there is no option to set it. Would it be possible to add it or is it tied to the jet mode that doesn't work yet? 

Thanks!

**Comment by JanM321** [comment]
> Unfortunately I see the medium-low and medium-high are not supported, even though the remote allows it. What happens if you send the command for these modes anyway? Will the unit just ignore them? How could I test this?

The unit will either ignore it or change it to one of the other values (I don't remember exactly). The protocol.md file has the list of fan speed values and even though low-medium and medium-high are in there, I haven't seen any unit actually support these values. Your C9 message also indicates it doesn't support these values.

The easiest way to test this is to change the value for Medium [here](https://github.com/JanM321/esphome-lg-controller/blob/9964e0ad8316ac971dcfcd284e475792635b8043/esphome/components/lg_controller/lg-controller.h#L734) from 1 to 5 or 6.

This is one of the worst things about the LG units, each controller (IR, wifi, wired) supports different features :/
